name: Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Run Tests
        run: flutter test -r expanded --coverage
